//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MOHU.Integration.Domain.Entitiy
{

	public partial class ldv_documentsetting 
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ldv_allowedextensions = "ldv_allowedextensions";
			public const string ldv_allowedsizeinkb = "ldv_allowedsizeinkb";
			public const string ldv_appearinworkspace = "ldv_appearinworkspace";
			public const string ldv_code = "ldv_code";
			public const string ldv_descriptionar = "ldv_descriptionar";
			public const string ldv_descriptionen = "ldv_descriptionen";
			public const string ldv_displayorder = "ldv_displayorder";
			public const string ldv_documentsettingId = "ldv_documentsettingid";
			public const string Id = "ldv_documentsettingid";
			public const string ldv_DocumentSettingsId = "ldv_documentsettingsid";
			public const string ldv_documenttypecode = "ldv_documenttypecode";
			public const string ldv_entityname = "ldv_entityname";
			public const string ldv_entityschemaname = "ldv_entityschemaname";
			public const string ldv_hastempelate = "ldv_hastempelate";
			public const string ldv_ismandatory = "ldv_ismandatory";
			public const string ldv_maximumallowedfiles = "ldv_maximumallowedfiles";
			public const string ldv_minimumallowedfiles = "ldv_minimumallowedfiles";
			public const string ldv_name = "ldv_name";
			public const string ldv_Name_Ar = "ldv_name_ar";
			public const string ldv_Name_En = "ldv_name_en";
			public const string ldv_origincode = "ldv_origincode";
			public const string ldv_remarkar = "ldv_remarkar";
			public const string ldv_remarken = "ldv_remarken";
			public const string ldv_sectionname = "ldv_sectionname";
			public const string ldv_servicesettingid = "ldv_servicesettingid";
			public const string ldv_servicestageid = "ldv_servicestageid";
			public const string ldv_ticketcategoryid = "ldv_ticketcategoryid";
			public const string ldv_ticketsubcategoryid = "ldv_ticketsubcategoryid";
			public const string ldv_validateinstageid = "ldv_validateinstageid";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		
		public const string EntityLogicalName = "ldv_documentsetting";
		
		public const string EntitySchemaName = "ldv_documentsetting";
		
		public const string PrimaryIdAttribute = "ldv_documentsettingid";
		
		public const string PrimaryNameAttribute = "ldv_name";
		
		public const string EntityLogicalCollectionName = "ldv_documentsettings";
		
		public const string EntitySetName = "ldv_documentsettings";
		

	}
}